apiVersion: apps/v1
kind: Deployment
metadata:
  name: bbb-stream
spec:
  replicas: 10
  selector:
    matchLabels:
      app: bbb-stream
  template:
    metadata:
      labels:
        app: bbb-stream
    spec:

      volumes:
        - name: bbb-video
          emptyDir: {}

      initContainers:
        - name: download-bbb
          image: appropriate/curl
          volumeMounts:
            - name: bbb-video
              mountPath: /video
          args:
            - -o
            - /video/bbb.flv
            - https://storage.googleapis.com/livepeerjs-public/bbb_sunflower_1080p_30fps_normal.cgop.flv

      containers:
        - name: ffmpeg
          image: jrottenberg/ffmpeg:4.1-ubuntu
          resources:
            requests:
              memory: 512Mi
          volumeMounts:
            - name: bbb-video
              mountPath: /video
          command:
            - /bin/bash
            - -c
            - echo 'starting in 5 seconds' && sleep 5 && ffmpeg -re -stream_loop -1 -i /video/bbb.flv -c:v copy -c:a copy -f flv rtmp://a220043f0704411e997ed02e6142e157-197261543.us-west-2.elb.amazonaws.com/stream/${HOSTNAME}
