
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "livepeer.fullname" . }}-api-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "livepeer.fullname" . }}-api-server
  labels:
    app.kubernetes.io/name: {{ include "livepeer.name" . }}-api-server
    helm.sh/chart: {{ include "livepeer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "livepeer.name" . }}-api-server
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "livepeer.name" . }}-api-server
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "livepeer.fullname" . }}-api-server
      containers:
        - name: {{ .Chart.Name }}-api-server
          image: "{{ .Values.images.api.repository }}:{{ .Values.images.api.tag }}"
          imagePullPolicy: {{ .Values.images.api.pullPolicy }}
          env:
            - name: LP_KUBE_BROADCASTER_SERVICE
              value: {{ include "livepeer.fullname" . }}-broadcaster
            - name: LP_KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if .Values.api.environment }}
            {{- toYaml .Values.api.environment | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "livepeer.fullname" . }}-api-server
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["endpoints"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
kind: RoleBinding
metadata:
  name: {{ include "livepeer.fullname" . }}-api-server
  namespace: default
subjects:
- kind: ServiceAccount
  name: {{ include "livepeer.fullname" . }}-api-server # Name is case sensitive
  apiGroup:
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: {{ include "livepeer.fullname" . }}-api-server # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
