apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "livepeer.fullname" . }}-broadcaster
  labels:
    app.kubernetes.io/name: {{ include "livepeer.name" . }}-broadcaster
    helm.sh/chart: {{ include "livepeer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "livepeer.name" . }}-broadcaster
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "livepeer.name" . }}-broadcaster
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-broadcaster
          image: "{{ .Values.images.goLivepeer.repository }}:{{ .Values.images.goLivepeer.tag }}"
          imagePullPolicy: {{ .Values.images.goLivepeer.pullPolicy }}
          args:
            - -broadcaster
            - -rtmpAddr=0.0.0.0:1935
            - -cliAddr=0.0.0.0:7935
            - -orchAddr={{ include "livepeer.fullname" . }}-transcoder-0.{{ include "livepeer.fullname" . }}-transcoder.default.svc.cluster.local:8935,{{ include "livepeer.fullname" . }}-transcoder-1.{{ include "livepeer.fullname" . }}-transcoder.default.svc.cluster.local:8935,{{ include "livepeer.fullname" . }}-transcoder-2.{{ include "livepeer.fullname" . }}-transcoder.default.svc.cluster.local:8935,{{ include "livepeer.fullname" . }}-transcoder-3.{{ include "livepeer.fullname" . }}-transcoder.default.svc.cluster.local:8935,{{ include "livepeer.fullname" . }}-transcoder-4.{{ include "livepeer.fullname" . }}-transcoder.default.svc.cluster.local:8935,{{ include "livepeer.fullname" . }}-transcoder-5.{{ include "livepeer.fullname" . }}-transcoder.default.svc.cluster.local:8935,{{ include "livepeer.fullname" . }}-transcoder-6.{{ include "livepeer.fullname" . }}-transcoder.default.svc.cluster.local:8935,{{ include "livepeer.fullname" . }}-transcoder-7.{{ include "livepeer.fullname" . }}-transcoder.default.svc.cluster.local:8935,{{ include "livepeer.fullname" . }}-transcoder-8.{{ include "livepeer.fullname" . }}-transcoder.default.svc.cluster.local:8935,{{ include "livepeer.fullname" . }}-transcoder-9.{{ include "livepeer.fullname" . }}-transcoder.default.svc.cluster.local:8935
            - transcodingOptions=P240p30fps16x9,P360p30fps16x9,P576p30fps16x9,P720p30fps16x9
          ports:
            - name: http
              containerPort: 7935
              hostPort: 80
              protocol: TCP
            - name: rtmp
              containerPort: 1935
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.broadcaster.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.broadcaster.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.broadcaster.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
