apiVersion: v1
kind: Service
metadata:
  name: {{ include "livepeer.fullname" . }}-broadcaster
  labels:
    app.kubernetes.io/name: {{ include "livepeer.name" . }}-broadcaster
    helm.sh/chart: {{ include "livepeer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
    - port: 1935
      targetPort: 1935
      protocol: TCP
      name: rtmp
  selector:
    app.kubernetes.io/name: {{ include "livepeer.name" . }}-broadcaster
    app.kubernetes.io/instance: {{ .Release.Name }}
