apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "livepeer.fullname" . }}-nvidia-driver-installer
data:
  install-nvidia-drivers.sh: |
    #!/bin/bash

    set -e
    set -x
    set -o nounset

    export DEBIAN_FRONTEND=noninteractive

    apt-get update 
    apt-get install -y software-properties-common gnutls-bin 
    add-apt-repository ppa:graphics-drivers/ppa 
    apt-get update

    apt-get install -qy libnvidia-compute-430 libnvidia-encode-430 libnvidia-decode-430 nvidia-driver-430

    distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
    curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
    curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
    sudo apt-get update && sudo apt-get install -y nvidia-docker2
    sudo systemctl restart docker

    echo "Done!"
