apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "livepeer.fullname" . }}-transcoder
  labels:
    app.kubernetes.io/name: {{ include "livepeer.name" . }}-transcoder
    helm.sh/chart: {{ include "livepeer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  serviceName: {{ include "livepeer.fullname" . }}-transcoder
  replicas: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "livepeer.name" . }}-transcoder
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "livepeer.name" . }}-transcoder
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - {{ include "livepeer.name" . }}-transcoder
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: {{ .Chart.Name }}-transcoder
          image: "{{ .Values.images.goLivepeer.repository }}:{{ .Values.images.goLivepeer.tag }}"
          imagePullPolicy: {{ .Values.images.goLivepeer.pullPolicy }}
          command:
            - /bin/bash
            - -c
          args:
            # - tail -f /dev/null
            - sleep 30 && /root/start.sh -orchestrator -transcoder -httpAddr=0.0.0.0:8935 -serviceAddr=${HOSTNAME}.{{ include "livepeer.fullname" . }}-transcoder.default.svc.cluster.local:8935
            # - cbs-demo-livepeer-transcoder-0.cbs-demo-livepeer-transcoder.default.svc.cluster.local
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: rtmp
              containerPort: 1935
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.transcoder.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.transcoder.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.transcoder.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
